variable "region" {}
variable "iam_user_name" {}
variable "bucket_name" {}
variable "root_domain" {}
variable "dns_record_ttl" {}
variable "website_bucket" {}
variable "force_destroy" {}
variable "versioning_enabled" {}
variable "index_document" {}
variable "admin_email" {}
variable "lambda_payload_filename" {}
variable "contact_api_stage" {}